trigger: none

name: $(Build.BuildId)

variables:
- name: AZP_AGENT_CLEANUP_PSMODULES_IN_POWERSHELL
  value: true

jobs:
  - job: build_job
    displayName: 'Build VSIX extension'
    pool: 
    # Can used MS hosted - it will be open source project
     vmImage: 'windows-latest'
    steps:
    # run the node run command
    - task: Npm@1
      displayName: 'Install packages using yarn'
      inputs:
        command: 'custom'
        workingDir: '$(Build.SourcesDirectory)'
        customCommand: 'run install_packages'
    - task: PowerShell@2
      displayName: 'Install typescript'
      inputs:
        targetType: 'inline'
        script: 'npm install -g typescript'
    # run build command to build the extension
    - task: Npm@1
      displayName: 'Compile typescript'
      inputs:
        command: 'custom'
        workingDir: '$(Build.SourcesDirectory)'
        customCommand: 'run compile_tasks'
    # build command using tfx-cli
    - task: TfxInstaller@4
      inputs:
        version: 'v0.x'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          
          Set-Location -Path $(Build.SourcesDirectory)

          tfx extension create --manifest-globs ./vss-extension.json

          mkdir vsix_output

          # Move the vsix file to the output folder
          Move-Item -Path ./*.vsix -Destination ./vsix_output
          
        pwsh: true
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact: vsix'
      inputs:
        targetPath: '$(Build.SourcesDirectory)/vsix_output'
        artifact: 'vsix'
        publishLocation: 'pipeline'