# AzureDevOpsFlutterTasksPack-Build
trigger: none

resources:
  pipelines:
    - pipeline: build_pipeline
      source: AzureDevOpsFlutterTasksPack-Build
      trigger: true

jobs:
- job: release_job
  displayName: 'Deploy extension to Azure DevOps Marketplace'
  pool: 
    vmImage: 'windows-latest'
  steps:
  - checkout: none
  - download: build_pipeline
    artifact: vsix
  - task: TfxInstaller@4
    inputs:
      version: 'v0.x'
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        
        Set-Location -Path $(Agent.BuildDirectory)/build_pipeline/vsix
        
        #rename the vsix first file
        $vsixFile = Get-ChildItem -Path .\*.vsix
        $newName = "AzureDevOpsFlutterTasksPack.vsix"
        Rename-Item -Path $vsixFile -NewName $newName

      pwsh: true
  - task: PublishAzureDevOpsExtension@4
    inputs:
      connectTo: 'VsTeam'
      connectedServiceName: 'MarketPlaceServiceConnection'
      fileType: 'vsix'
      vsixFile: '$(Agent.BuildDirectory)/build_pipeline/vsix/AzureDevOpsFlutterTasksPack.vsix'
      updateTasksVersion: false
      extensionVisibility: 'private'